server:
  port: 8080

spring:
  application:
    name: SimianCheck
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
          jdbc: 
            lob:  
              non_contextual_creation: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test